import express from "express";
import dotenv from "dotenv";
import cors from "cors";
import cookieParser from "cookie-parser";
import path from "path";

import { connectDB } from "./db/connectDB.js";

import authRoutes from "./routes/auth.route.js";

dotenv.config();

const app = express();
const PORT = process.env.PORT || 5000;
const __dirname = path.resolve();

app.use(cors({ origin: "http://localhost:5173", credentials: true }));

app.use(express.json()); // allows us to parse incoming requests:req.body
app.use(cookieParser()); // allows us to parse incoming cookies

app.use("/api/auth", authRoutes);


// Serve frontend files in production
if (process.env.NODE_ENV === "production") {
	// Serve the static files generated by the React frontend build process
	// These files (HTML, CSS, and JS) are stored in the "frontend/dist" directory
	app.use(express.static(path.join(__dirname, "/frontend/dist")));

	// Catch-all route to handle SPA (Single Page Application) routing
	// Any request that doesn't match an API route will serve "index.html"
	// This allows React to handle the routing on the client side
	app.get("*", (req, res) => {
		res.sendFile(path.resolve(__dirname, "frontend", "dist", "index.html"));
	});
}


app.listen(PORT, () => {
	connectDB();
	console.log("Server is running on port: ", PORT);
});
